name: anytalk_meme
description: Generate one-liners (memes) from a keyword via OpenAI.
publish_to: "none"

environment:
  sdk: ">=3.9.0 <4.0.0"   # Dart 3.9 stable

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0            # latest http

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0   # latest lint set
